language: java

matrix:
  include:
    - jdk: openjdk6
      env: IDEA_VERSION="14.0.4" COVERALLS=true
    - jdk: oraclejdk8
      env: IDEA_VERSION="14.0.4"
    - jdk: openjdk6
      env: IDEA_VERSION="143.249.6"

install: ./gradlew -P ideaVersion=$IDEA_VERSION assemble

script: ./gradlew -P ideaVersion=$IDEA_VERSION build

after_success: if [ "$COVERALLS" == "true" ]; then ./gradlew -P ideaVersion=$IDEA_VERSION jacocoTestReport coveralls; fi
