dist: bionic

language: java

matrix:
  include:
    - jdk: oraclejdk8
      env: IDEA_VERSION="2019.1.4" COVERALLS=true SONARQUBE=true
    - jdk: oraclejdk8
      env: IDEA_VERSION="2019.2.4"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2019.3"
    - jdk: oraclejdk8
      env: IDEA_VERSION="2020.1"
    - jdk: openjdk11
      env: IDEA_VERSION="2020.1"
    - jdk: oraclejdk8
      env: IDEA_VERSION="LATEST-EAP-SNAPSHOT"
    - jdk: openjdk11
      env: IDEA_VERSION="LATEST-EAP-SNAPSHOT"
  allow_failures:
    - jdk: oraclejdk8
      env: IDEA_VERSION="LATEST-EAP-SNAPSHOT"
    - jdk: openjdk11
      env: IDEA_VERSION="LATEST-EAP-SNAPSHOT"

install: ./gradlew -P ideaVersion=$IDEA_VERSION assemble

script: ./gradlew -P ideaVersion=$IDEA_VERSION build

after_success:
  - if [ "$COVERALLS" == "true" ]; then ./gradlew -P ideaVersion=$IDEA_VERSION cobertura coveralls; fi
  - if [ "$SONARQUBE" == "true" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN; fi
