name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * *' # every day 8am

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
            idea: 2020.2.3
          - java: 11
            idea: 2020.2.3
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew -P ideaVersion=${{ matrix.idea }} build
