name: Plugin compatibility
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build the plugin using Gradle
      run: ./gradlew buildPlugin
    - uses: thepieterdc/intellij-plugin-verifier-action@v1.1.1
      with:
        plugin: '/home/runner/work/idea-gradle-dependencies-formatter/idea-gradle-dependencies-formatter/build/distributions/idea-gradle-dependencies-formatter-*'
        versions: |
          2019.1.4
          2019.2.4
          2019.3.4
          2020.1
          LATEST-EAP-SNAPSHOT
